// sessionTexts.ts
import type { Session, SessionContent } from "./types"
import type { Pomo } from "./types";

export const sessionTexts: Record<Session, SessionContent & { pomo: Pomo }> = {
    diverge: {
    name: "발산",
    target: "자유롭게 아이디어 확장",
    effect: "다양한 아이디어 확보",
    energy: "2",
    features: ["아이디어 발산", "자유 탐색"],
    guide: "제약 없이 최대한 많이 아이디어를 내보세요",
    pomo: "basic",
    time : '25분',
  },
  converge: {
    name: "수렴",
    target: "아이디어를 좁히고 구체화",
    effect: "실행 가능한 아이디어 정리",
    energy: "2",
    features: ["아이디어 정리", "우선순위 결정"],
    guide: "발산된 아이디어 중 핵심만 추려냅니다",
    pomo: "basic",
    time : '25분',
  },
  observe: {
    name: "관찰",
    target: "현상/대상 관찰",
    effect: "새로운 인사이트 확보",
    energy: "1",
    features: ["패턴 관찰", "데이터 기록"],
    guide: "주변 환경과 현상을 세밀히 관찰합니다",
    pomo: "basic",
    time : '25분',
  },
  screening: {
    name: "스크리닝",
    target: "아이디어 후보 정리 및 선별",
    effect: "발산된 아이디어 중 실현 가능/효과 큰 것 선별",
    energy: "2",
    features: ["아이디어 필터링", "중요도 평가"],
    guide: "다수의 아이디어를 빠르게 평가하고, 버릴 것/살릴 것을 표시",
    pomo: "refine",
    time : '25분',
  },
  refine: {
    name: "정밀 조율",
    target: "최종 디테일 조정, 완성도 확보",
    effect: "결과물 퀄리티 향상",
    energy: "2",
    features: ["디테일 체크", "최종 다듬기"],
    guide: "형태, 색, 구조 등 세부 요소를 점검하고 조정",
    pomo: "refine",
    time : '25분',
  },
  reverse: {
    name: "뒤집기 사고",
    target: "기존 구조를 재배치, 새로운 관점 도출",
    effect: "설득력 있는 구조, 의도 명확화",
    energy: "2",
    features: ["구조 재배치", "논리 전환"],
    guide: "아이디어나 메시지를 뒤집어 새로운 배치를 시도, 예상 결과와 비교",
    pomo: "reverse",
    time : '25분',
  },
  constraint: {
    name: "제약 도입",
    target: "랜덤 아이디어를 현실적 구조로 적용",
    effect: "창의적 + 실행 가능 아이디어 변형",
    energy: "2",
    features: ["무작위 요소 제한", "현실적 적용"],
    guide: "무작위 발상에 규칙/제약을 넣어 현실적 가능성을 검토",
    pomo: "random",
    time : '25분',
  },
  emotion: {
    name: "감정 기록",
    target: "감정을 글/이미지/메모로 기록",
    effect: "감정 인식, 표현, 작업에 반영",
    energy: "2",
    features: ["감정 캡처", "기록 도구"],
    guide: "지금 느끼는 감정을 기록하고, 이를 시각/텍스트로 표현",
    pomo: "emotion",
    time : '25분',
  },
  tagging: {
    name: "아이디어 태깅",
    target: "발산된 아이디어를 키워드/카테고리로 분류",
    effect: "탐구 과정 정리, 후속 연결 용이",
    energy: "2",
    features: ["키워드 분류", "아이디어 라벨링"],
    guide: "생각나는 아이디어에 태그를 붙여 탐색 경로와 연관성 기록",
    pomo: "explore",
    time : '25분',
  },
  structuring: {
    name: "구조화",
    target: "스토리/컨텐츠 흐름 설계",
    effect: "시청자/사용자가 흐름 이해 가능",
    energy: "2",
    features: ["순서 설계", "흐름 체크"],
    guide: "전체 내용을 단계별로 배치하고 연결 관계 점검",
    pomo: "story",
    time : '25분',
  },
  analysis: {
    name: "반응 분석",
    target: "작업/자극에 대한 내 반응 관찰",
    effect: "자기 인식, 감정 기반 피드백 확보",
    energy: "1",
    features: ["기록", "감정 변화 그래프"],
    guide: "작업 진행 중 느낀 감정/반응을 기록하고 패턴 확인",
    pomo: "echo",
    time : '25분',
  },
  ruleBreaking: {
    name: "규칙 탈착",
    target: "기존 규칙/습관 벗어나기",
    effect: "새롭고 실험적인 시도, 창작 확장",
    energy: "3",
    features: ["규칙 제거", "제한 해제"],
    guide: "기존 틀을 벗어나 과감히 변형, 재해석",
    pomo: "escape",
    time : '25분',
  },
  transformation: {
    name: "변형",
    target: "발산 아이디어를 반복적 변형",
    effect: "깊이 있는 탐구, 다양한 형태 실험",
    energy: "2",
    features: ["반복 루프", "아이디어 변형"],
    guide: "기존 아이디어를 여러 관점에서 수정/변형하며 발전",
    pomo: "repeat",
    time : '25분',
  },
  break: {
    name: "단기휴식",
    target: "숨 돌리기",
    effect: "스트레스 해소, 감각 회복",
    energy: "1",
    features: ["감각 정화", "비움"],
    guide: "머릿속 생각을 자유롭게 흘려보내고, 최소한의 행동/표현으로 감각 유지",
    pomo: "empty",
    time : '5분',
  },
  detox: {
    name: "장기휴식",
    target: "감정/머리 비우기, 휴식 겸 창작 준비",
    effect: "리프레시",
    energy: "1",
    features: ["숨 돌리기"],
    guide: "머릿속 생각을 자유롭게 흘려보내고, 최소한의 행동/표현으로 감각 유지",
    pomo: "empty",
    time : '25분',
  },
};
